lee=[ "Among the vicissitudes incident to life, no event could have filled me with greater anxieties than that of which the notification was transmitted by your order and received on the fourteenth day of the present month.", " On the one hand, I was summoned by my Country, whose voice I can never hear but with veneration and love, from a retreat which I had chosen with the fondest predilection, and, in my flattering hopes, with an immutable decision, as the asylum of my declining years: a retreat which was rendered every day more necessary as well as more dear to me, by the addition of habit to inclination, and of frequent interruptions in my health to the gradual waste committed on it by time.", " On the other hand, the magnitude and difficulty of the trust to which the voice of my Country called me, being sufficient to awaken in the wisest and most experienced of her citizens, a distrustful scrutiny into his qualification, could not but overwhelm with dispondence, one, who, inheriting inferior endowments from nature and unpractised in the duties of civil administration, ought to be peculiarly conscious of his own deficencies.", " In this conflict of emotions, all I dare aver, is, that it has been my faithful study to collect my duty from a just appreciation of every circumstance, by which it might be affected.", " All I dare hope, is, that, if in executing this task I have been too much swayed by a grateful remembrance of former instances, or by an affectionate sensibility to this transcendent proof, of the confidence of my fellow-citizens; and have thence too little consulted my incapacity as well as disinclination for the weighty and untried cares before me; my error will be palliated by the motives which misled me, and its consequences be judged by my Country, with some share of the partiality in which they originated.", "

Such being the impressions under which I have, in obedience to the public summons, repaired to the present station; it would be peculiarly improper to omit in this first official Act, my fervent supplications to that Almighty Being who rules over the Universe, who presides in the Councils of Nations, and whose providential aids can supply every human defect, that his benediction may consecrate to the liberties and happiness of the People of the United States, a Government instituted by themselves for these essential purposes: and may enable every instrument employed in its administration to execute with success, the functions allotted to his charge.", " In tendering this homage to the Great Author of every public and private good, I assure myself that it expresses your sentiments not less than my own; nor those of my fellow-citizens at large, less than either.", " No People can be bound to acknowledge and adore the invisible hand, which conducts the Affairs of men more than the People of the United States.", " Every step, by which they have advanced to the character of an independent nation, seems to have been distinguished by some token of providential agency.", " And in the important revolution just accomplished in the system of their United Government, the tranquil deliberations and voluntary consent of so many distinct communities, from which the event has resulted, cannot be compared with the means by which most Governments have been established, without some return of pious gratitude along with an humble anticipation of the future blessings which the past seem to presage.", " These reflections, arising out of the present crisis, have forced themselves too strongly on my mind to be suppressed.", " You will join with me I trust in thinking, that there are none under the influence of which, the proceedings of a new and free Government can more auspiciously commence.", "

By the article establishing the Executive Department, it is made the duty of the President "to recommend to your consideration, such measures as he shall judge necessary and expedient.", " The circumstances under which I now meet you, will acquit me from entering into that subject, farther than to refer to the Great Constitutional Charter under which you are assembled; and which, in defining your powers, designates the objects to which your attention is to be given.", " It will be more consistent with those circumstances, and far more congenial with the feelings which actuate me, to substitute, in place of a recommendation of particular measures, the tribute that is due to the talents, the rectitude, and the patriotism which adorn the characters selected to devise and adopt them.", " In these honorable qualifications, I behold the surest pledges, that as on one side, no local prejudices, or attachments; no seperate views, nor party animosities, will misdirect the comprehensive and equal eye which ought to watch over this great assemblage of communities and interests: so, on another, that the foundations of our National policy will be laid in the pure and immutable principles of private morality; and the pre-eminence of a free Government, be exemplified by all the attributes which can win the affections of its Citizens, and command the respect of the world."]
word1=dict()
word2=dict()
num1=[0,0,0,0,0,0,0,0,0,0]
wordlist1=["","","","","","","","","",""]
num2=[0,0,0,0,0,0,0,0,0,0]
wordlist2=["","","","","","","","","",""]
def countwords(lee,num1,word1,wordlist1):
    for i in lee:
        words=i.", "lower()
        words=words.", "split()
        for l in words:
            if l not in word1:
                word1[l]=1
            else:
                word1[l]=word1[l]+1
    for i in word1:
        for number in range(0,10):
            if word1[i]>num1[number]:
                num1[number]=word1[i]
                wordlist1[number]=i
                break
    print num1
    print wordlist1
countwords(lee,num1,word1,wordlist1)
countwords(add2,num2,word2,wordlist2)